# 이슈 발생

- 현재 백앤드 서버를 연동해줘도 바르게 작동하지 않는 모습이 발견됐다. 원인은 뭘까...

## 시도한 것

- settings.py 세팅 변경
- url postman으로 테스트해보기
